
CREATE FUNCTION sync_lastmod() RETURNS trigger AS $$
BEGIN
  NEW.last_updated := NOW();

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE categories (
    id UUID PRIMARY KEY,
    title VARCHAR NOT NULL,
    icon VARCHAR NOT NULL,
    color CHAR(6) NOT NULL,
    event_id SERIAL REFERENCES events(id),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX ON categories (event_id);

CREATE TRIGGER
  sync_lastmod
BEFORE UPDATE ON
  categories
FOR EACH ROW EXECUTE PROCEDURE
  sync_lastmod();


ALTER TABLE entries
    ADD "begin" TIMESTAMP WITH TIME ZONE NOT NULL,
    ADD "end" TIMESTAMP WITH TIME ZONE NOT NULL,
    ADD category UUID REFERENCES categories(id),
    ADD deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

CREATE TRIGGER
  sync_lastmod
BEFORE UPDATE ON
  entries
FOR EACH ROW EXECUTE PROCEDURE
  sync_lastmod();


ALTER TABLE rooms
    ADD deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

CREATE TRIGGER
  sync_lastmod
BEFORE UPDATE ON
  rooms
FOR EACH ROW EXECUTE PROCEDURE
  sync_lastmod();
