---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: rust:latest
    commands:
      - cargo build --verbose --all
    depends_on:
      - clone

  - name: rust test
    image: rust:latest
    commands:
      - cargo test --verbose --all
    depends_on:
      - build

  - name: system tests
    image: mcr.microsoft.com/playwright/python:v1.55.0-noble
    commands:
      # Java is required for openapi-generator
      - apt-get update && apt-get install -y libpq5 postgresql-client-16 openjdk-21-jre-headless
      - pip install openapi-generator-cli
      - cd tests
      - pip install -r requirements.txt
      - pytest --browser firefox --browser chromium --start-app
    environment:
      DATABASE_URL: postgres://kueaplan:password@postgres/kueaplan_tests
      SECRET: test_secret
    depends_on:
      - build

  - name: clippy
    image: rust:latest
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets --all-features
    depends_on:
      - rust test

  - name: fmt
    image: rust:latest
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
    depends_on:
      - clone

  - name: python-fmt
    image: python:3.13-slim-trixie
    commands:
      - pip install mypy ruff
      - ruff check
      - ruff format --check
      - cd tests
      - pip install -r requirements.txt
      - mypy
    depends_on:
      - clone

services:
  - name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: kueaplan
      POSTGRES_DB: kueaplan_tests
      LANG: de_DE.utf8
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=de-DE

trigger:
  branch:
    - main
    - ci/*
